language: r
r:
  - release
warnings_are_errors: false
os:
  - linux
  - osx
env:
  - RSERVE=Rserve
branches:
  only:
    master
    
addons:
  apt:
    packages:
      - libssh2-1-dev

before_script:
  - echo `ls -la`
  - cd ..; mv Rserve* Rserve; cd Rserve; sh mkdist -i
  - echo `ls -la`
  - cd ..; mv Rserve Rserve-src; tar zxvf Rserve_*.tar.gz; cd Rserve
  - echo `ls -la`

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo chown -R $(whoami) /usr/local ; brew install libgit2; fi
  
after_success:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'covr::codecov()'; fi
  
before_deploy:
  - if [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then git tag "$TRAVIS_OS_NAME" --force; fi
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi

deploy:
  provider: releases
  name: "$TRAVIS_OS_NAME"
  api_key:
    secure: "lxbU0MSoVH7cduiL/fw6kZHT5Y/dsZE+RvbPohOPNKgh7NrvR+ztf10Y96uDcrDp14GS1pyrUqZjKYA21m2X4ntPzCZcoTl3yw6/BgGD9U7Mbv7/j85c5qnGXHjHN0gFXkOjj9CKjjauHIB7DvRHbWZD4M9eLyHlrwSD0PUxQkYa6O4rQsUEuICKNFdGcvbybHyzG7TG3/L7EiXpdMw9SPpQtIvF2AdhNu5ldsgqBCtGNx/3jPVV5/TIEuORXmHB+xcBPftK0Yz90yueYdLwFkGD8gQWswqdq7HR1oEel8bAvYCNDLxeOBRHHkk8MnlP1SkLQCjLKqdBC+JhwbindP6Bkg9FU8tfLshn0vtZq1ctitEFQ+Fjsocryc+1dotLd/t6QquBalZytlcLIU5Om163hZsANdTcjLTl/QWZFnsD0pgpYDbCmKMgNrgpe3yZhLWW+EUi0nAikdvLzwKcqi4KnGiV2HmxM1xT7NkCzA8IxKFgrKYG2F7SOANsg3YmG8dsVVXn2gt3tGfE3oBcLlRTbIf6wgvU4hrFOzUTARp+c9b3BP9IKI0qNEszgI4gD6A3fqefGysk4d/NiEyQujWxhwdAtI+JfjynX7h1iXv0X4fZfwwH5E33Oi0e7CfsmkkmHA+CQVZvVNh3QxdjScKaiRUO9Y/r4qDtJOToZJs="
  file_glob: true
  file: Rserve*.t*gz
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    except: windows
