language: r
r:
  - release
warnings_are_errors: false
os:
  - linux
  - osx
branches:
  only:
    master
    
addons:
  apt:
    packages:
      - libssh2-1-dev

before_script:
  - echo `ls -la`
  - cd ..; mv Rserve* Rserve; cd Rserve
  - echo `ls -la`
  - sh mkdist -i
  - cd ..; mv Rserve Rserve-src; tar zxvf Rserve_*.tar.gz
  - echo `ls -la`
  - cd Rserve

before_install:
  - echo "$TRAVIS_OS_NAME"
  - echo "$TRAVIS_R_VERSION_STRING"
  - echo $PKG_TARBALL
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo chown -R $(whoami) /usr/local ; brew install libgit2; fi
  
after_success:
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'covr::codecov()'; fi
  
before_deploy:
  - if [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then git tag "$TRAVIS_OS_NAME" --force; fi
  - if [[ "$TRAVIS_R_VERSION_STRING" == "release" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi

deploy:
  provider: releases
  name: "$TRAVIS_OS_NAME"
  api_key:
    secure: "RerLjYsUdfSRvCzUNFZCjIftJ9P7xr+aJE8IWCyMIND9P7MyE2M3vII1sAiwRg2WG92bs5MO/UJ+0XooK1gWHyLl+z1CNvhZvD+fdLrQOkjEL62MSoaFZxHqsAZYHF++HvSVj32LrKy2lIYLWwWGPjR8fXW8S6G9pDfLCm2d+JUPgMIXKa/HuJauoSzLF68QCXHfnYeaJC444nZU7AutnvqIWkr62DAJr8fQSsUYl9fpOtdJHDsyedPHbpBHYKeaWd/yantmEPFiE66mBYXBgjqhBAGRbb3OZEFxqplQlc6l0DPxaxJj+XTL2WSrDrjgjzYLd/0cngfu/UwMwzMmkH0+xU8/5/i5Ay3LmcRCgwugKnscQZA1eni7v/tgnNkF1QDpvj1P1Lbn+x0F5CFztzAR0Zdzn95HZDhT2mOUVa0ip228f0DBEFu4Q6i1hxVpIUJJGEvt080ooeUBIyUtU7SfhsGC0ee7QpbhbJjt5OipQosOsZotKMhKOqlaobDAzTvmbhUmoGoW15PVuhRHbLDizeDE9iFtPtWG8tEldJPpJpdxTo+EwIjiZkK0+tEbWti2BVpJNMf4CBCUGtv1qu2gcCJUz7krEKh4G0AInVwHx975sjgKwHpefJEnEH0IguHH8BQB7CGhB3tpgNhj6j9M2lLibD6qXJ/gkwpv9Mg="
  file_glob: true
  file: Rserve*.t*gz
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    except: windows
    condition: "$TRAVIS_R_VERSION_STRING = release"
