#!/bin/sh

SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/Rserve
echo "Copying package base ..."
cp -r ../Rserve /tmp

#touch /tmp/Rserve/src/dummy.so
rm -f /tmp/Rserve/mkdist

cd /tmp/Rserve
# mkdir inst
if [ -e configure ]; then
  echo "Note: configure exists, no attempt to reconfigure will be made."
else
  echo "Running autoconf ..."
  aclocal
  autoheader
  autoconf
  rm -rf autom4te* aclocal*
fi

echo "Removing CVS/SVN and backup stuff ..."
find . -name CVS -o -name \*~ -o -name .svn|xargs rm -rf

# copy header files so they are available to the client
cp src/Rsrv.h src/include/sisocks.h src/client/cxx/

if [ -e src/client/cxx/configure.ac ]; then
    if [ ! -e src/client/cxx/configure ]; then
	cd src/client/cxx
	echo "Running autoconf in cxx..."
	aclocal
	autoheader
	autoconf
	rm -rf autom4te* aclocal*
	cd /tmp/Rserve
    fi
fi

rm -rf clients
ln -s src/client clients

(cd src/client/java-new; make && make -C Rserve)

# no INDEX since 1.8
#echo "Updating INDEX ..."
#cd ..
#R CMD Rdindex Rserve > Rserve/INDEX
#rm -f Rserve/INDEX
#cd Rserve

echo "Updating version ..."
VER=`./version`
echo "Rserve version ${VER}"
cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
mv d DESCRIPTION
echo "Creating package ..."
cd ..
# do NOT use build - it screws up symbolic links
#R CMD build --force Rserve
tar fcz Rserve_${VER}.tar.gz Rserve
cd ${SWD}
cp /tmp/Rserve_${VER}.tar.gz ..
rm -rf /tmp/Rserve
echo "Done."
ls -l ../Rserve_${VER}.tar.gz
