#!/bin/sh

SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/Rserve
echo "Copying package base ..."
cp -r ../Rserve /tmp

touch /tmp/Rserve/src/dummy.so
rm -f /tmp/Rserve/mkdist

echo "Running autoconf ..."
cd /tmp/Rserve
mkdir inst
autoheader
autoconf
rm -rf autom4te*

echo "Removing CVS and backup stuff ..."
rm -rf `find . -name CVS`
rm -f `find . -name \*~`

# no INDEX since 1.8
#echo "Updating INDEX ..."
#cd ..
#R CMD Rdindex Rserve > Rserve/INDEX
#rm -f Rserve/INDEX
#cd Rserve

echo "Updating version ..."
VER=`awk -v ORS= '/Rserve v/ { print substr($6,2) }' src/Rsrv.h`
echo "Rserve version ${VER}"
cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
mv d DESCRIPTION
echo "Creating package ..."
cd ..
tar fcz Rserve_${VER}.tar.gz Rserve
cd ${SWD}
cp /tmp/Rserve_${VER}.tar.gz ..
rm -rf /tmp/Rserve
echo "Done."
ls -l ../Rserve_${VER}.tar.gz
