#!/bin/sh

SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/Rserve
echo "Copying package base ..."
cp -r ../Rserve /tmp

#touch /tmp/Rserve/src/dummy.so
rm -f /tmp/Rserve/mkdist

cd /tmp/Rserve
mkdir inst
if [ -e configure ]; then
  echo "Note: configure exists, no attempt to reconfigure will be made."
else
  echo "Running autoconf ..."
  aclocal
  autoheader
  autoconf
  rm -rf autom4te* aclocal*
fi

echo "Removing CVS/SVN and backup stuff ..."
find . -name CVS -o -name \*~ -o -name .svn|xargs rm -rf

# no INDEX since 1.8
#echo "Updating INDEX ..."
#cd ..
#R CMD Rdindex Rserve > Rserve/INDEX
#rm -f Rserve/INDEX
#cd Rserve

echo "Updating version ..."
VER=`./version`
echo "Rserve version ${VER}"
cat DESCRIPTION| sed "s/Version:.*/Version: ${VER}/" > d
mv d DESCRIPTION
echo "Creating package ..."
cd ..
tar fcz Rserve_${VER}.tar.gz Rserve
cd ${SWD}
cp /tmp/Rserve_${VER}.tar.gz ..
rm -rf /tmp/Rserve
echo "Done."
ls -l ../Rserve_${VER}.tar.gz
